#ifndef GAME_H_

#define GAME_H_

#define WND_TITLE L"GDIdemo9 - ≈≈–ÚÃ˘Õº"
#define WND_CLASS L"GDIdemo9"

CONST UINT WND_WIDTH = 800;
CONST UINT WND_HEIGHT = 600;
CONST INT WND_POSX = 300;
CONST INT WND_POSY = 150;

CONST UINT SPRITE_COUNT = 4;
CONST UINT SPRITE_NUMBERS = 30;

extern "C" LRESULT CALLBACK WndProc(HWND hwnd, UINT message, WPARAM wParam, LPARAM lParam);

#endif